---
abstract: 'L<DBIx::Class> plugin for automatically tracking lineage paths in simple data trees.'
author:
  - 'Ashley Pond V · ashley.pond.v@gmail.com · L<http://pangyresoft.com>.'
  - 'Ashley Pond V <ashley@cpan.org>'
build_requires:
  DBICx::TestDatabase: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBICx-MaterializedPath
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBICx::TestDatabase: 0
  DBIx::Class: 0.081
  Test::More: 0.42
  parent: 0.2
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pangyre/p5-dbicx-materializedpath
version: 0.02
