---
abstract: 'L<DBIx::Class> plugin for automatically tracking lineage paths in simple data trees (beta software).'
author:
  - 'Ashley Pond V <ashley.org>'
build_requires:
  DBICx::TestDatabase: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBICx-MaterializedPath
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Class: 0.081
  parent: 0.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
